### ISSUE TITLE
Invalid link in the "Should You Learn to Code?" minigame

### ISSUE THREAD

**Issue by SamMed05** [BloombergGraphics/whatiscode#160]
When you finish the game in the "Should You Learn to Code?" section, two blue buttons appear at the bottom. The one on the right ("Or just Google it") opens in a new tab a Google search with the following broken link:
https://www.google.com/#q=javascript%20array%20tutorial

The correct link should be:
https://www.google.com/search?q=javascript%20array%20tutorial

**Comment by Rahmattullah13** [comment]
can i sign this??
